services:
  client:
    build:
      context: .
    container_name: bill_generator_client
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: bill_generator_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS}
      - APP_TIER_IP=${APP_TIER_IP}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - client

volumes:
  caddy_data:
